-- MySQL Script generated by MySQL Workbench
-- Thu Jun 28 00:15:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sys
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `school` ;

-- -----------------------------------------------------
-- Table `school`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`student` (
  `student_id` INT(11) NOT NULL,
  `student_name` VARCHAR(45) NOT NULL,
  `student_birthday` VARCHAR(10) NOT NULL,
  `create_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `school`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`professor` (
  `professor_id` INT(11) NOT NULL,
  `professor_name` VARCHAR(45) NOT NULL,
  `professor_birthday` VARCHAR(10) NOT NULL,
  `create_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`professor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `school`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`subject` (
  `subject_id` INT(11) NOT NULL,
  `subject_name` VARCHAR(45) NOT NULL,
  `create_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `subject_professor_id` INT(11) NOT NULL,
  PRIMARY KEY (`subject_id`),
  INDEX `fk_subject_professor_idx` (`subject_professor_id` ASC),
  CONSTRAINT `fk_subject_professor`
    FOREIGN KEY (`subject_professor_id`)
    REFERENCES `school`.`professor` (`professor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `school`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`grade` (
  `grade_id` INT(11) NOT NULL AUTO_INCREMENT,
  `grade_score` VARCHAR(10) NOT NULL,
  `create_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `grade_student_id` INT(11) NOT NULL,
  `grade_subject_id` INT(11) NOT NULL,
  PRIMARY KEY (`grade_id`),
  INDEX `fk_grade_student1_idx` (`grade_student_id` ASC),
  INDEX `fk_grade_subject1_idx` (`grade_subject_id` ASC),
  CONSTRAINT `fk_grade_student1`
    FOREIGN KEY (`grade_student_id`)
    REFERENCES `school`.`student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_grade_subject1`
    FOREIGN KEY (`grade_subject_id`)
    REFERENCES `school`.`subject` (`subject_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
